#!/bin/bash

PROJECT_ROOT="$(cd "$(dirname "$0")"; cd ..; pwd)"
source ${PROJECT_ROOT}/config.sh

docker run -it \
    --name ${DOCKER_CONTAINER_NAME} \
    --volume ${PROJECT_ROOT}/ros2_ws:/ros2_ws \
    --network ${DOCKER_NETWORK} \
    --rm \
    ${DOCKER_IMAGE_NAME}
